import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css'
import { Toaster } from "@/components/ui/toaster";
import Navbar from '@/components/Navbar';
import AuthProvider from "@/context/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children, pageProps
}: {
  children: React.ReactNode,
  pageProps?: any
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
        <Toaster />
      </AuthProvider>
    </html>
  )
}
